### PR TITLE
Added the docs guidelines 

### PR DESCRIPTION
**Pull request by RustyRaptor**
Just broad ideas to keep the docs easy to maintain and helpful to newcomers. #5

### CODE REVIEW

**Comment by ghost** [comment]
would be nice if you linked that file in the main README.md nibba.

**Comment by RustyRaptor** [comment]
Oh yeah for sure. Now lemme look up how to do that lmoa.

**Comment by RustyRaptor** [comment]
Alright it's in. I put it under contributing in a subheading.

**Comment by ghost** [comment]
Much better, thanks m8

**Pull request merged**
